# Generated by Django 2.1.1 on 2018-10-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_playsong_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
